# The name is the same as the ClusterIssuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <domain>
spec:
  secretName: <domain>
  issuerRef:
    name: <domain>-private
    kind: ClusterIssuer
  dnsNames:
    - <domain>
    - '*.<domain>'
    - '*.local.<domain>'
    - '*.dev.<domain>'
    - '*.staging.<domain>'
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: '' # Sync certificate to all namespaces
      # kubed.appscode.com/sync: 'sync-cert-tls=true' # Sync certificate to all namespaces that matched the label
